[global]
# All input and output files are stored in this directory
workdir = examples/hello_world/
# Queue: hirescps | kpfcc
queue = kpfcc
# Today's date
current_day = 2025-08-06
# Semester start date
semester_start_day = 2025-08-02
# Semester end date
semester_end_day = 2026-01-31
# Semester ID
semester = 2025B
# Hours difference: local time minus UT (negative = local behind UT, e.g. -10 for HST)
UTCoffset = -10

[data]
allocation_file = prepped/allocation.csv
past_file = prepped/past.csv
programs_file = programs.csv
request_file = prepped/request.csv
custom_file = prepped/custom.csv
# name of filler file (not implemented for hello world)
filler_file = prepped/fillers.csv

[semester]
# Size of one slot, in minutes
slot_size = 10
# Specify a random seed. In the paper for weather testing, we use 24 through 33
random_seed = 24
# Scheduling mode: shortfall | shortfall,balance,prioritize,fill-empty,fill-current-day
mode = shortfall
# Conversion between awarded nights and total hours
hours_per_night = 12.0

[semester.default.gurobi]
TimeLimit = 300
MIPGap = 0.05
OutputFlag = 0
NoRelHeurTime = 0
Presolve = 1
MIPFocus = 0
DegenMoves = -1

[semester.shortfall.gurobi]
OutputFlag = 1

[night]
# % gap between optimal and current solution to stop the solve
max_solve_gap = 0.05
# Maximum time that can be spent solving the model
max_solve_time = 300
# Show the Gurobi output in the terminal
show_gurobi_output = True
