"""Generate the semester- and program-level statistics tables.

Reads the final-stage run report recorded in data/01/ and writes two AASTeX
deluxetables:

    table_semester.tex   semester-level totals
    table_programs.tex   per-program awards, projections, and fill shortfall

Both are GENERATED; edit this script rather than the .tex output.

Usage:
    python tools/make_tables.py
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.dirname(HERE)
DATA = os.path.join(PAPER, "data", "01")
REPORT = "baseline-report-final.txt"

SLOT_MINUTES = 2

# Semester-level rows to show, in order, with the label used in the table.
# Several report lines are redundant on the first night (nothing is past yet),
# so only the informative ones are carried over.
SEMESTER_ROWS = [
    ("Total requests", "Requests submitted", None),
    ("Total requests (active)", "Requests active", None),
    ("Total requests (active, future slots > 0)", "Requests schedulable", None),
    ("Total slots requested (active)", "Time requested", "hours"),
    ("Total allocated slots", "Time allocated", "hours"),
    ("Future reserved slots", "Time scheduled", "hours"),
    ("Future fill factor", "Semester fill factor", "percent"),
    ("Current day allocated slots", "Time allocated, first night", "hours"),
    ("Current day reserved slots", "Time scheduled, first night", "hours"),
    ("Current day fill factor", "Fill factor, first night", "percent"),
]

# Programs that are bookkeeping rather than science.
FILLER = "2026B_E475"
EMPTY = "2026B_C362"


def read_report():
    with open(os.path.join(DATA, REPORT)) as fh:
        return fh.read()


def semester_scalars(text):
    out = {}
    for line in text.splitlines():
        m = re.match(r"^(.*?)\s{2,}(\d+)$", line)
        if m:
            out[m.group(1).strip()] = int(m.group(2))
    return out


def program_rows(text):
    rows = []
    for line in text.splitlines():
        parts = line.split()
        if not parts or not parts[0].startswith("2026B_"):
            continue
        rows.append({
            "program": parts[0],
            "aw": float(parts[1]), "req": float(parts[2]),
            "past": float(parts[3]), "proj": float(parts[4]),
            "proj_pct": parts[8].rstrip("%"),
            "maff_pct": parts[9].rstrip("%"),
            "fsf_pct": parts[10].rstrip("%"),
        })
    return rows


def write_semester(stats):
    lines = [
        "% GENERATED by tools/make_tables.py -- do not edit by hand.",
        "\\begin{deluxetable}{lr}",
        "\\tablecaption{Semester-level statistics for the 2026B HIRES queue,"
        " as planned on the first night\\label{tab:semester}}",
        "\\tablehead{\\colhead{Quantity} & \\colhead{Value}}",
        "\\startdata",
    ]
    for key, label, unit in SEMESTER_ROWS:
        if key not in stats:
            continue
        raw = stats[key]
        if unit == "hours":
            value = f"{raw * SLOT_MINUTES / 60:.1f} hr"
        elif unit == "percent":
            value = f"{raw}\\%"
        else:
            value = f"{raw:d}"
        lines.append(f"{label} & {value} \\\\")
    lines[-1] = lines[-1].rstrip(" \\\\")
    lines += [
        "\\enddata",
        "\\tablecomments{Time is reported in hours, converted from the"
        f" \\param{{pipeline-slot-minutes}}~min scheduling slot. Requested time"
        " counts every visit a PI asked for and so exceeds the allocation;"
        " see \\S\\ref{sec:balance:nocompete}. The fill factor is the fraction"
        " of allocated time occupied by a scheduled visit.}",
        "\\end{deluxetable}",
        "",
    ]
    path = os.path.join(PAPER, "table_semester.tex")
    with open(path, "w") as fh:
        fh.write("\n".join(lines))
    return path


def write_programs(rows):
    lines = [
        "% GENERATED by tools/make_tables.py -- do not edit by hand.",
        "\\begin{deluxetable*}{lrrrrrr}",
        "\\tablecaption{Program-level statistics for the 2026B HIRES queue,"
        " as planned on the first night\\label{tab:programs}}",
        "\\tablehead{",
        "  \\colhead{Program} & \\colhead{$A_p$} & \\colhead{Requested} &",
        "  \\colhead{Projected} & \\colhead{\\Fp} & \\colhead{\\maff} &",
        "  \\colhead{\\fsf} \\\\",
        "  \\colhead{} & \\colhead{(hr)} & \\colhead{(hr)} & \\colhead{(hr)} &",
        "  \\colhead{(\\%)} & \\colhead{(\\%)} & \\colhead{(\\%)}",
        "}",
        "\\startdata",
    ]
    for row in rows:
        name = row["program"].replace("2026B_", "")
        if row["program"] == FILLER:
            name += "\\tablenotemark{a}"
        elif row["program"] == EMPTY:
            name += "\\tablenotemark{b}"
        fsf = row["fsf_pct"] if row["fsf_pct"] != "-" else "\\nodata"
        lines.append(
            f"{name} & {row['aw']:.1f} & {row['req']:.1f} & {row['proj']:.1f}"
            f" & {row['proj_pct']} & {row['maff_pct']} & {fsf} \\\\"
        )
    lines[-1] = lines[-1].rstrip(" \\\\")
    lines += [
        "\\enddata",
        "\\tablenotetext{a}{Filler backstop. Its award is nominal rather than"
        " allocated time and it is excluded from queue totals.}",
        "\\tablenotetext{b}{No requests submitted.}",
        "\\tablecomments{$A_p$ is the award, derived from the Keck blocks"
        " assigned to each program. \\Fp is the projected fill, \\maff the"
        " maximum feasible fill, and $\\fsf = \\maff - \\Fp$ the fill"
        " shortfall of Equation~\\ref{eq:fsf}. H402 and Y063 exceed 100\\%"
        " because stages 3--5 raise the ceiling to"
        " \\param{pipeline-maxfill-late}, letting them absorb time U258"
        " cannot use (\\S\\ref{sec:balance:mismatch}).}",
        "\\end{deluxetable*}",
        "",
    ]
    path = os.path.join(PAPER, "table_programs.tex")
    with open(path, "w") as fh:
        fh.write("\n".join(lines))
    return path


if __name__ == "__main__":
    text = read_report()
    print("wrote", write_semester(semester_scalars(text)))
    print("wrote", write_programs(program_rows(text)))
