[global]
# All input and output files are stored in this directory
workdir = examples/priorities/bench/
queue = kpfcc
# Name of the observatory
observatory = Keck Observatory
# Today's date
current_day = 2018-08-05
# Semester start date
semester_start_day = 2018-08-01
# Semester end date
semester_end_day = 2019-01-31
# Semester ID
semester = 2018B

[data]
allocation_file = allocation.csv
past_file = past.csv
programs_file = programs.csv
request_file = request.csv
custom_file = custom.csv
# name of filler file (not implemented at this time)
filler_file = fillers.csv

[semester]
# Size of one slot, in minutes
slot_size = 5
# Specify a random seed. In the paper for weather testing, we use 24 through 33
random_seed = 24
# Scheduling mode: shortfall | shortfall,balance,prioritize,fill-empty,fill-current-day
mode = shortfall,balance,prioritize,fill-empty,fill-current-day
# Conversion between awarded nights and total hours
hours_per_night = 10.0

[semester.default.gurobi]
TimeLimit = 300
MIPGap = 0.01
OutputFlag = 0
NoRelHeurTime = 0
Presolve = 1
MIPFocus = 0
DegenMoves = -1

[semester.shortfall.gurobi]
NoRelHeurTime = 30
OutputFlag = 1
Presolve = 2
MIPFocus = 1

[semester.balance.gurobi]
OutputFlag = 1

[semester.prioritize]
hold_fill_alpha = 0.0

[semester.prioritize.gurobi]
OutputFlag = 1

[semester.fill-empty]
throttle_grace = 2.0

[semester.fill-empty.gurobi]
OutputFlag = 1

[semester.fill-current-day]
global_shortfall_slack = 1.1

[semester.fill-current-day.gurobi]
Presolve = 1

[night]
# % gap between optimal and current solution to stop the solve
max_solve_gap = 0.01
# Maximum time that can be spent solving the model
max_solve_time = 3600
# Show the Gurobi output in the terminal
show_gurobi_output = True
