[global]
# All input and output files are stored in this directory
workdir = examples/priorities/symmetric_toy_model/
queue = kpfcc
# Name of the observatory
observatory = Keck Observatory
# Today's date
current_day = 2018-08-05
# Semester start date
semester_start_day = 2018-08-01
# Semester end date
semester_end_day = 2019-01-31
# Semester ID
semester = 2018B

[data]
# name of allocation file 
allocation_file = allocation.csv
# name of past history file 
past_file = past.csv
# name of the programs file
programs_file = programs.csv
# name of request file 
request_file = request.csv
# name of custom file 
custom_file = custom.csv
# name of filler file (not implemented at this time)
filler_file = fillers.csv

[semester]
method = milp

# Size of one slot, in minutes
slot_size = 5
# Run a weather loss model in the autoscheduler
run_weather_loss = False
# Specify a random seed. In the paper for weather testing, we use 24 through 33
random_seed = 24
# Scheduling mode: round1 (Round 1 only) or full (Rounds 1-5)
mode = full
# % gap between optimal and current solution to stop the solve
max_solve_gap = 0.01
# Maximum time that can be spent solving the model
max_solve_time = 3600
# Show the Gurobi output in the terminal
show_gurobi_output = True
# Conversion between awarded nights and total hours
hours_per_night = 10.0

[night]
# % gap between optimal and current solution to stop the solve
max_solve_gap = 0.01
# Maximum time that can be spent solving the model
max_solve_time = 3600
# Show the Gurobi output in the terminal
show_gurobi_output = True
